/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from 'kysely'

export type Generated<T> =
  T extends ColumnType<infer S, infer I, infer U>
    ? ColumnType<S, I | undefined, U>
    : ColumnType<T, T | undefined, T>

export type Timestamp = ColumnType<Date, Date | string, Date | string>

export interface Test {
  id: Generated<string>
}

export interface Users {
  created_at: Generated<Timestamp>
  deleted_at: Timestamp | null
  email: string
  email_verified: Timestamp | null
  id: Generated<string>
  image: string | null
  mobile_phone_number: string | null
  name: string | null
  role: string
  updated_at: Generated<Timestamp>
}

export interface DB {
  test: Test
  users: Users
}
