version: '3.4'
services:
  postgres:
    container_name: postgres_api
    image: postgres:14.1-alpine3.15
    ports:
      - 5432:5432
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
volumes:
  db_data:
