// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ColumnType, Selectable, Insertable, Updateable } from 'kysely'

import type { UsersId } from './Users'

/** Identifier type for public.accounts */
export type AccountsId = string & { __brand: 'AccountsId' }

/** Represents the table public.accounts */
export default interface AccountsTable {
  id: ColumnType<AccountsId, AccountsId | null, AccountsId | null>

  userId: ColumnType<UsersId, UsersId, UsersId | null>

  type: ColumnType<string, string, string | null>

  provider: ColumnType<string, string, string | null>

  providerAccountId: ColumnType<string, string, string | null>

  refresh_token: ColumnType<string | null, string | null, string | null>

  access_token: ColumnType<string | null, string | null, string | null>

  expires_at: ColumnType<string | null, string | null, string | null>

  token_type: ColumnType<string | null, string | null, string | null>

  scope: ColumnType<string | null, string | null, string | null>

  id_token: ColumnType<string | null, string | null, string | null>

  session_state: ColumnType<string | null, string | null, string | null>
}

export type Accounts = Selectable<AccountsTable>

export type NewAccounts = Insertable<AccountsTable>

export type AccountsUpdate = Updateable<AccountsTable>
