// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ColumnType, Selectable, Insertable, Updateable } from 'kysely'

/** Identifier type for public.organisations */
export type OrganisationsId = string & { __brand: 'OrganisationsId' }

/** Represents the table public.organisations */
export default interface OrganisationsTable {
  id: ColumnType<
    OrganisationsId,
    OrganisationsId | null,
    OrganisationsId | null
  >

  name: ColumnType<string, string, string | null>

  referencePrefix: ColumnType<string | null, string | null, string | null>
}

export type Organisations = Selectable<OrganisationsTable>

export type NewOrganisations = Insertable<OrganisationsTable>

export type OrganisationsUpdate = Updateable<OrganisationsTable>
