// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { default as KyselyMigrationTable } from './KyselyMigration'
import type { default as KyselyMigrationLockTable } from './KyselyMigrationLock'
import type { default as UsersTable } from './Users'

export default interface PublicSchema {
  kysely_migration: KyselyMigrationTable

  kysely_migration_lock: KyselyMigrationLockTable

  users: UsersTable
}
