// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { default as UsersTable } from './Users'
import type { default as KyselyMigrationLockTable } from './KyselyMigrationLock'
import type { default as KyselyMigrationTable } from './KyselyMigration'

export default interface PublicSchema {
  users: UsersTable

  kysely_migration_lock: KyselyMigrationLockTable

  kysely_migration: KyselyMigrationTable
}
