// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Represents the enum public.user_role */
enum UserRole {
  SUPPORT = 'SUPPORT',
  SALES = 'SALES',
  CS = 'CS',
}

export default UserRole
