// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type UserRole from './UserRole'
import type { ColumnType, Selectable, Insertable, Updateable } from 'kysely'

/** Identifier type for public.users */
export type UsersId = string & { __brand: 'UsersId' }

/** Represents the table public.users */
export default interface UsersTable {
  id: ColumnType<UsersId, UsersId | null, UsersId | null>

  name: ColumnType<string | null, string | null, string | null>

  email: ColumnType<string, string, string | null>

  emailVerified: ColumnType<
    Date | null,
    Date | string | null,
    Date | string | null
  >

  image: ColumnType<string | null, string | null, string | null>

  mobilePhoneNumber: ColumnType<string | null, string | null, string | null>

  role: ColumnType<UserRole, UserRole, UserRole | null>

  createdAt: ColumnType<Date, Date | string | null, Date | string | null>

  updatedAt: ColumnType<Date, Date | string | null, Date | string | null>

  deletedAt: ColumnType<Date | null, Date | string | null, Date | string | null>
}

export type Users = Selectable<UsersTable>

export type NewUsers = Insertable<UsersTable>

export type UsersUpdate = Updateable<UsersTable>
