name: Lint and Test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup node and package manager
        uses: ./.github/actions/setup-node-and-package-manager

      - name: Install bun dependency to run tests
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies 📦
        uses: ./.github/actions/pnpm-install

      - name: Run lint
        run: pnpm lint

      - name: Run unit tests
        run: pnpm test

      - name: Setup database
        run: |
          sudo apt-get update
          sudo apt-get install -y postgresql-client

          until pg_isready -h localhost -p 5432 -U postgres; do
            echo "Waiting for Pg..."
            sleep 2
          done

          PGPASSWORD=postgres psql -h localhost -p 5432 -U postgres -d local_db -c "CREATE EXTENSION fuzzystrmatch;"

      - name: Run integration tests
        env:
          DATABASE_URL: postgres://postgres:postgres@localhost:5432/local_db
        run: pnpm test:integration
